MODEL:
  ARCHITECTURE: "TRM"
  TRM:
    NUM_CLIPS: 64
    JOINT_SPACE_SIZE: 256
    RESIDUAL: 0.1
    FEATPOOL:
      INPUT_SIZE: 500
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 4
    FEAT2D:
      NAME: "pool"
      POOLING_COUNTS: [15, 8, 8]
    TEXT_ENCODER:
      NAME: "BERT"
      USE_PHRASE: True
    PREDICTOR:
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 9
      NUM_STACK_LAYERS: 4
    LOSS:
      MIN_IOU: 0.5
      MAX_IOU: 1.0
      NUM_POSTIVE_VIDEO_PROPOSAL: 1
      NEGATIVE_VIDEO_IOU: 0.5
      SENT_REMOVAL_IOU: 0.5
      TAU_VIDEO: 0.1
      TAU_SENT: 0.1
      MARGIN: 0.3
      CONTRASTIVE_WEIGHT: 0.01
      SENT_NEG_IOU: 0.5
      NEGATIVE_PROP_IOU: 0.5
      PHRASE_ONLY: False
      USE_SCORE_MAP_LOSS: True
      USE_FOCAL_LOSS: True
      CONTRASTIVE: True
      CONSIS_WEIGHT: 0.1
      EXC_WEIGHT: 0.1
      THRESH: 0.2
DATASETS:
  NAME: "activitynet"
  TRAIN: ("activitynet_train", )
  TEST: ("activitynet_test","activitynet_test_verb")
INPUT:
  NUM_PRE_CLIPS: 256
DATALOADER:
  NUM_WORKERS: 16
SOLVER:
  LR: 0.0008
  BATCH_SIZE: 20
  MILESTONES: (15,)
  MAX_EPOCH: 18
  TEST_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  RESUME: False
  RESUME_EPOCH: 10
  FREEZE_BERT: 4
  ONLY_IOU: 6
  SKIP_TEST: 0
TEST:
  NMS_THRESH: 0.5
  BATCH_SIZE: 24
  CONTRASTIVE_SCORE_POW: 0.5
